import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { BoardProvider } from "@/context/BoardContext";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="bg-[#F0F0F0] h-20 flex justify-center items-center sticky top-0 z-50">
                    <h1 className="text-4xl text-black font-bold">
                        DND Board: Seamless Task Management
                    </h1>
                </header>
                <BoardProvider>{children}</BoardProvider>
            </body>
        </html>
    );
}
